### ISSUE TITLE
Update demo

### ISSUE THREAD

**Issue by lilfolr** [lilfolr/react-timeline-9000#29]
Demo should include:
- [x] Zoom controls
- [x] Left & Right buttons
- [ ] Add/Remove selected activity

**Comment by lilfolr** [comment]
@vasdee Let me know if you think of anything else the demo should have

**Comment by vasdee** [comment]
close it for now since it's in done.

**Comment by jaballogian** [comment]
> Demo should include:
> 
> * [x]  Zoom controls
> * [x]  Left & Right buttons
> * [ ]  Add/Remove selected activity

Is the remove selected activity feature done?
I don't know how to remove the selected item from the demo.
I tried to press the delete button from the keyboard or press the right mouse button but did nothing.
